os: osx
language: shell

matrix:
  include:
    - name: macOS 10.15 (Catalina)
      osx_image: xcode11.5
    - name: macOS 10.14 (Mojave)
      osx_image: xcode11.3
    - name: macOS 10.13 (High Sierra)
      osx_image: xcode10.1
  fast_finish: true

install:
  - brew install composer php7.3 shellcheck
  - composer install --prefer-dist --no-suggest

script:
  - composer test
